### PR TITLE
Auto Refreshing Item

### PR DESCRIPTION
**Pull request by meatballs**
- [x] Implementation Code
- [x] Documentation
- [x] Example use in demo
- [x] override dict.update

### CODE REVIEW

**Comment by s-cork** [comment]
Not necessarily part of this pr but we could make utils a lazy module and use the `__dir__` to expose the available attributes. I think meredydd added the feature so that a module with a `__dir__` comes up in the autocomplete

**Comment by s-cork** [comment]
I don't know how important it is but overriding `__setitem__` isn't enough to trigger a refresh if you use `dict.update`. Might be a nice bonus.

**Comment by meatballs** [comment]
> Not necessarily part of this pr but we could make utils a lazy module and use the `__dir__` to expose the available attributes. I think meredydd added the feature so that a module with a `__dir__` comes up in the autocomplete

I think this one ought to be a separate issue and pr.

**Review by s-cork — APPROVED** [review]
Lgtm

**Comment by meatballs** [comment]
I'll put a new release together some time today.

**Pull request merged**
