### PR TITLE
add a lazy module loader and load marshmallow using it

### LINKED ISSUE #212: Serialisation module on the free plan
**Describe the bug**
At the moment the development branch breaks free user accounts for server calls
All server modules are loaded on a server call including the serialisation module
On the free plan marshmallow is not available which will throw an error

**To Reproduce**
- depend on the development branch
- switch to python basic 
- call a server function

**Additional context**
We should probably lazy load marshmallow anyway for performance reasons.
(given that the serialisation module will be imported for each server call)

**I am considering making a PR for this issue**
Assuming @meatballs will want to take this.

### PR DESCRIPTION
**Pull request by s-cork**
close #212

### CODE REVIEW

**Comment by s-cork** [comment]
fixes the immediate issue - merging

**Comment by meatballs** [comment]
Nice job!

**Comment by s-cork** [comment]
@meatballs feel free to clean anything that isn't how you'd write it.
I tried to make the pr without moving too many flowers around the garden so to speak

**Comment by meatballs** [comment]
All looks perfectly good to me

**Pull request merged**
