### PR TITLE
Template paths and redirects

### PR DESCRIPTION
**Pull request by s-cork**
@jshaffstall 

attempt number 2.

Maybe you could have a play with it by cloning this version of anvil-extras:
https://anvil.works/build#clone:6ATPRINDTZUXBKSQ=R3XKGGOVQZK6MZVHG36HCTLU

Then changing the dependency to the local copy while we still work out the kinks.

I changed a bunch of logging statements as I was working on it to make it easier to see what was going on.

The api is the one we came up with on the other branch:

```python
@routing.redirect(...) # same args as template
def redirect_no_admin():
    # routing.set_url_hash("login", ...)
    # or return a url_hash
    return "login"

```

### CODE REVIEW

**Comment by jshaffstall** [comment]
Not sure what is wrong with this: https://anvil.works/build#clone:KFF6KEV4NDMJJK5U=JI5EORBERTEDFD7AG4O5WTGW

When I run it under the regular development version of anvil_extras, it shows the public home page when run.  When run under the clone version it does not show the home page.  I've commented out the redirect and login template for now.

**Comment by s-cork** [comment]
oh sugar - that should be fixed now - trying to prevent an infinite loop caused the first loop to not execute!

Fixed - 

if you're git savy you can clone the anvil-extras-dev locally
clone this repo locally
and do some git incantations rather than recloning

**Comment by jshaffstall** [comment]
Uncommented out the redirect and login router.

The login router intercepts correctly when trying to go to any of its routes.  

The first run I got an error about self.current not existing in login_click, but after that one run it worked fine.  Not sure what that was about.

The redirect decorator works great, non-admins are getting redirected to `#user`.

As far as I can tell from the setup I have, it all seems to be working fine.  This technique reduces the number of template conditions needed by quite a bit.  I only have conditions on my login router and my no admin redirect.  By the time it gets to the user or admin routers, I already know the user is logged in and is an admin if they're trying to go to the admin pages.

**Comment by s-cork** [comment]
So we're calling this branch a win.

I'll give it another once over later today
add some docs
and it'll be ready for review

side note - i see you're using/experimenting with Tabulator.
Definitely move to version v2.1.0 if you can - it's recently gone through a rewrite.

**Comment by jshaffstall** [comment]
Yeah, I wrote another sample app that included some pages and sidebar links, and everything worked as expected.  Definitely a win.

**Comment by s-cork** [comment]
@jshaffstall this is now on the development branch
keep us posted on anything you notice in your experiments!

**Pull request merged**
