### PR TITLE
Routing - add a redirect argument to templates

### PR DESCRIPTION
**Pull request by s-cork**
@jshaffstall - take a look - what do you think?

There's a choice about how the redirect should work
I went with 

```python
            set_url_hash(
                redirect, replace_current_url=True, set_in_history=False, redirect=True
            )
```
But I could see an argument for `set_in_history=True`.

### CODE REVIEW

**Comment by jshaffstall** [comment]
I'm concerned about the template redirect hiding valid 404 results.  

Before the redirect url was available valid URLs would get marked as not being valid (false positives).  The redirect solves that.

With the redirect invalid URLs will be redirected instead of being marked as not valid (false negatives).  This seems like a problem.  If `#user/account` is a valid page on my site, but they don't have permissions to see it, the redirect should happen.  But if they go to `#user/foo`, which is not a page on my site, I'd expect the error form to trigger.  

Detecting that, though, would require going through every page registered to the template in the `elif redirect is not None:` block and redirecting only if the URL matched a page.  

Unless I'm overthinking this?

**Comment by jshaffstall** [comment]
I guess the behavior is different depending on the web app.  Blackboard, a course management system, does the opposite,  you get a login page for valid protected URLs, and a 404 page for invalid protected URLs.  The more I think about it, I guess it doesn't really matter, so the current behavior works fine.   As long as we avoid marking valid URLs as invalid, which the redirect does. 

Another thing to think about.  Some web apps, when you try to go to a protected URL, will redirect to the login page.  Then when you login they take you to the original protected URL you were trying to go to.  Before templates with conditions that would be managed in forms.   

With conditional templates, is there a way to get to the original URL hash before the redirect?

**Comment by jshaffstall** [comment]
It strikes me that if there were a way to have wildcard url patterns, everything we're trying to do with redirects could be handled with a high priority login template that used wildcard url patterns to match all protected areas with a condition of the user not being logged in, as long as the login template could get to the original URL to redirect to after login.  Other sorts of protected areas could have a similar gatekeeping template.

Not trying to advocate for one or the other approach; just trying to workout if redirects are the easiest way to solve the issue.

**Comment by s-cork** [comment]
I've thought about wild card patterns - then stopped short when trying to implement them.

Do you have a pattern in mind about how you'd like to use it?

There are a couple of ways i'd currently implement a catch all for a login template that could redirect to the original url after login.

**Comment by jshaffstall** [comment]
For what I was suggesting, just * would be enough, as long as multiple template routes could be specified

```
@routing.template(path=["admin/*", "account/*"], priority=20, condition=lambda: Globals.user is None)
class RouterLogin(RouterLoginTemplate):
```

That template could then redirect to the original url after login, or to the home page if the login was cancelled.

**Comment by s-cork** [comment]
That wouldn't need the * no?
Just a way to define multiple paths?

Once that existed how would you envisage the rest of the code. 

Currently I'd do something like. 

```python
@template(path=[...], ...)
class LoginRouter(...):
    def on_navigation(self, url_hash,...):
    self.current = url_hash
        routing.set_url_hash("login", replace_current=True, set_in_history=False, redirect=False)
    raise routing.NavigationExit
    # don't change my content panel 

def login_btn_click(self, **event_args):
    # login user
    routing.set_url_hash(self.current)
```python

**Comment by jshaffstall** [comment]
Yeah, that was a brain dead moment.  Template urls are already an implicit * match at the end.

Given a way to match multiple urls for a template, I think we're good.  That should remove the need for the redirects.  

The same technique should be useful for pages that require higher levels of privilege than just being logged in.  This template would be processed at a lower priority than the login one and can redirect to a suitable page (assuming that setting the url hash inside on_navigation transfers to a new template)  or display an error message:

```
@template(path=[...], condition=lambda: not Globals.user['admin'])
class NotAdminRouter(...):
    def on_navigation(self, url_hash,...):
        routing.set_url_hash("", replace_current=True)
```

**Comment by s-cork** [comment]
Yeap that could work. I'd need to think about redirecting the url_hash in that situation. 

And might be better just to do that type of immediate redirect in the `__init__` method. 

I'd need to make sure it doesn't end up doing the equivalent of `open_form()` within the `__init__` of the current open form. 

i.e how to raise a NavigationExit implicitly when the current navigation get superseded by a new call to set_url_hash. But that shouldn't be too difficult.

**Comment by jshaffstall** [comment]
Yeah, ideally the redirect would happen before the current form shows.  I hadn't thought `__init__` would work because of the limitation on opening another form in there.

It feels odd defining a template form whose purpose is to never get shown.

**Comment by s-cork** [comment]
Yeah it does feel odd. What's the point in making it a form?

That example should work but - it's possible a new api might be better suited here.

You could register a redirect class method.

```python
@redirect(path=[], ...)
def no_admin_redirect():
   routing.set_url_hash(..., )

# or as a class
@redirect(path=[], priority=20...)
class NoAdminRedirect:
    def __init__(self):
        routing.set_url_hash(..., )
```

and a redirect I guess could do nothing? And that would be ok?
Or if a redirect is invoked as part of navigation then we expect the redirect to actually redirect. 

Redirects would just be called along with template depending their priority. 
 
It would essentially be like a template but it would never become the open_form since it's not a form.

**Comment by jshaffstall** [comment]
I like the redirect function/class idea.  That'd work great.

If a redirect function doesn't actually redirect, would routing continue with the next lower priority template?  If so, I think it's fine to not require the redirect to happen.  I'm coming up short trying to work out when that would be useful (everything I think of can just be done as part of the redirect condition), but it wouldn't hurt to allow it.  Maybe someone will come up with a clever use for it. 

Returning the url hash/None/False makes sense, since it's a function designed to redirect, and that saves some typing.

**Comment by s-cork** [comment]
Superseded by #298

**Pull request closed without merging**
