### PR TITLE
Manage error during title formatting

### PR DESCRIPTION
**Pull request by stenci**
This will show a helpful error message instead of just
interrupting the page load with a generic error message.

### CODE REVIEW

**Comment by s-cork** [comment]
@stenci - lgtm you'll need to follow the [contribution](https://anvil-extras.readthedocs.io/en/latest/guides/contributing.html) guide the paragraph about pre-commit


```
pip install pre-commit
pre-commit install
pre-commit run --all-filles # in future you won't need this because it'll just work on each commit
```

**Comment by stenci** [comment]
The automatic formatting fails, but has nothing to do with my change.
I think it fails because some new lines are removed, meaning the module was already not compliant with the automatic formatting.

I personally don't like the formatting from `black`, but I can comply with it and reformat old code that I have not written (and make it less readable) for the sake of making it work.

**Comment by s-cork** [comment]
Have you tried using precommit - there's only one formatting error and its because line 199 is too long.
there is also a fail because of the fstring.

If you're happy I can just push that change as I have your branch locally

**Comment by meatballs** [comment]
Well, @meatballs hates pointless debates about layout and formatting but does like those to be consistent!

**Comment by stenci** [comment]
Sorry, I did format it yesterday, then today I restarted from scratch the fork-clone-etc., and I pasted the code with single quotes without reformatting it.

I think the problem is the line is too long and it uses single quotes rather than double quotes.
Do I need to create another PR?
Or is it possible to change this one?

I still can't run the pre-commit checks on my computer. Is it possible to run them on my fork before I commit to my fork?

I tried formatting the file in [this playground](https://black.vercel.app/), but it removes a bunch of new lines from the old code.

I tried your steps, but `pip` failed (because I use Anaconda).

I tried using `conda` instead of `pip`, but it fails:
```
(anvil) C:\workspace\Anvil\Anvil Extras\github>pre-commit install
pre-commit installed at C:\workspace\Anvil\Anvil Extras\github\.git\hooks\pre-commit

(anvil) C:\workspace\Anvil\Anvil Extras\github>pre-commit run --all-files
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/pycqa/isort.
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
[INFO] Initializing environment for https://github.com/Lucas-C/pre-commit-hooks.
[INFO] Installing environment for https://gitlab.com/pycqa/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('C:\\Users\\stefanomenci\\AppData\\Local\\conda\\conda\\envs\\anvil\\python.exe', '-mvirtualenv', 'C:\\Users\\stefanomenci\\.cache\\pre-commit\\repo4h_5rowi\\py_env-python3.6', '-p', 'C:\\ProgramData\\Anaconda3\\python.exe')
Return code: 1
Expected return code: 0
Output:
    StopIteration:

Errors: (none)

Check the log at C:\Users\stefanomenci/.cache\pre-commit\pre-commit.log
```

This is the log:
```
An unexpected error has occurred: CalledProcessError: Command: ('C:\\Users\\stefanomenci\\AppData\\Local\\conda\\conda\\envs\\anvil\\python.exe', '-mvirtualenv', 'C:\\Users\\stefanomenci\\.cache\\pre-commit\\repo4h_5rowi\\py_env-python3.6', '-p', 'C:\\ProgramData\\Anaconda3\\python.exe')
Return code: 1
Expected return code: 0
Output: 
    StopIteration: 
    
Errors: (none)

Traceback (most recent call last):
  File "C:\Users\stefanomenci\AppData\Local\conda\conda\envs\anvil\lib\site-packages\pre_commit\error_handler.py", line 47, in error_handler
    yield
  File "C:\Users\stefanomenci\AppData\Local\conda\conda\envs\anvil\lib\site-packages\pre_commit\main.py", line 261, in main
    return run(runner, store, args)
  File "C:\Users\stefanomenci\AppData\Local\conda\conda\envs\anvil\lib\site-packages\pre_commit\commands\run.py", line 268, in run
    repo.require_installed()
  File "C:\Users\stefanomenci\AppData\Local\conda\conda\envs\anvil\lib\site-packages\pre_commit\repository.py", line 195, in require_installed
    _install_all(self._venvs(), self.repo_config['repo'], self.store)
  File "C:\Users\stefanomenci\AppData\Local\conda\conda\envs\anvil\lib\site-packages\pre_commit\repository.py", line 102, in _install_all
    language.install_environment(prefix, version, deps)
  File "C:\Users\stefanomenci\AppData\Local\conda\conda\envs\anvil\lib\site-packages\pre_commit\languages\python.py", line 142, in install_environment
    _make_venv(env_dir, python)
  File "C:\Users\stefanomenci\AppData\Local\conda\conda\envs\anvil\lib\site-packages\pre_commit\languages\python.py", line 154, in make_venv
    cmd_output(*cmd, env=env, cwd='/')
  File "C:\Users\stefanomenci\AppData\Local\conda\conda\envs\anvil\lib\site-packages\pre_commit\util.py", line 186, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('C:\\Users\\stefanomenci\\AppData\\Local\\conda\\conda\\envs\\anvil\\python.exe', '-mvirtualenv', 'C:\\Users\\stefanomenci\\.cache\\pre-commit\\repo4h_5rowi\\py_env-python3.6', '-p', 'C:\\ProgramData\\Anaconda3\\python.exe')
Return code: 1
Expected return code: 0
Output: 
    StopIteration: 
    
Errors: (none)
```

I can't ask you to debug my machine configuration, but... well, any suggestion?
Should I create a Linux virtual machine and see if it works in there?

**Comment by s-cork** [comment]
I pushed the commit and merged.
@stenci - https://stackoverflow.com/questions/65192345/calledprocesserror-with-git-pre-commit-hook
that might help?
Seems to be a conda thing.

**Pull request merged**
